### ISSUE TITLE
UndefinedFunctionException  Attempted to call function "get_option" from the global namespace.

### ISSUE THREAD

**Issue by vnt** [bitpay/prestashop-v2#2]
Hi, 
When I try to make a payment with bitpay I get this error:

module/bitpaycheckout/bitpayorder

> (1/1)  UndefinedFunctionException                                                                  Attempted to call function "get_option" from the global namespace.
> --
> in bitpayorder.php line 85
> at BitpayCheckoutBitpayorderModuleFrontController->postProcess()in Controller.php line 270
> at ControllerCore->run()in Dispatcher.php line 511
> at DispatcherCore->dispatch()in index.php line 28
> 

BitPay Checkout v. 1.8.0 settings:
Production Enviornment: Yes
Modal Checkout: No
Auto-capture email: yes
Prestashop 1.7.5.1

**Comment by PWCH** [comment]
in file: \controllers\front\bitpayorder.php line 85

`$bitpay_token = get_option('bitpay_checkout_token_prod');`

change on:

`$bitpay_token = Configuration::get('bitpay_checkout_token_prod');`

**Comment by thejoshualewis** [comment]
Thanks, issue has been fixed
