### ISSUE TITLE
Updating order status

### ISSUE THREAD

**Issue by PWCH** [bitpay/prestashop-v2#4]
Plugin don't update order status after payment/cancelled/timeout. I think that is problem with redirect in bitpaycheckout.php or /controllers/front/ipn.php

Prestashop 1.7.6 

Maybe change status as variable in configuration? Then each store could determine how it should display.

**Comment by thejoshualewis** [comment]
Hi @PWCH ,

Added this option in the admin, it will default to "6", which is "Canceled" in a standard Prestashop install

**Comment by PWCH** [comment]
@thejoshualewis 
In BO the IPN Map status cannot be changed. Statuses aren't displayed.

In bitpaycheckout.php line 161
`'query' => $this->getOrderStates(),` 
change on
`'query' => OrderState::getOrderStates((int)$this->context->language->id),` (displayed but doesn't save selected status)

But it isn't the main problem :/

After 15minutes (timeout), after redirect to shop you see:
![image](https://user-images.githubusercontent.com/23063264/66031378-9345d280-e503-11e9-966f-18ec8ab22dae.png)
After payment still is 'Processing in progress'
