### ISSUE TITLE
Error in browser console

### ISSUE THREAD

**Issue by vnt** [bitpay/prestashop-v2#5]
Hi,
In the browser console, there is the following error:
1. Console bitpay.js: It looks like you may be loading bitpay.js in an unconvential way. We highly recommend that you load bitpay.js by adding '<script src="https://bitpay.com/bitpay.min.js"></script>' to your webpage. This will ensure that you get access to new features and product updates as they become available.

**Comment by thejoshualewis** [comment]
Hi @vnt ,
The warning is fine, its because it loading using // instead of specifying the protocol
