### ISSUE TITLE
The plugin is not working properly

### ISSUE THREAD

**Issue by vnt** [bitpay/prestashop-v2#6]
The plugin is not working properly.

When I place an order and choose to pay with bitpay, the modal for payment with bitpay does not open and the order is set as paid

**Comment by PWCH** [comment]
You have an additional language version enabled? I use it in shop without additional language and it work. But in the second shop with additional language doesn't 👎 
shop.com -> it work
second.shop.com/en/ -> doesn't work, after order it redirect to shop home page
@thejoshualewis

**Comment by vnt** [comment]
I have only one language (italian) enabled in the frontend

**Comment by PWCH** [comment]
Set 'No' Modal Checkout and Auto-Capture Email in configuration:
![image](https://user-images.githubusercontent.com/23063264/67188595-ecab6e00-f3ec-11e9-8407-681f2055d45f.png)
![image](https://user-images.githubusercontent.com/23063264/67188603-f46b1280-f3ec-11e9-8eb9-66d307ae27e3.png)
Then it should redirect you to the payment page. But will continue to incorrectly assign statuses.
